# Generated by Django 2.0.3 on 2018-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thegame',
            name='game_data',
        ),
        migrations.AddField(
            model_name='thegame',
            name='data',
            field=models.CharField(default='', max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thegame',
            name='x',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thegame',
            name='y',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
